package progettoscuola;

import DB.DbConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author Emanuel
 */
public class GUIMain extends javax.swing.JFrame {
  static String scelta;
    DbConnection connesione= new DbConnection();
    
    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        initComponents();
    }
      JButton btn;
      JTextArea txtpopup;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        userNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jbtCerca = new javax.swing.JButton();
        jbtPC = new javax.swing.JButton();
        jbtNintendo = new javax.swing.JButton();
        jbtPS4 = new javax.swing.JButton();
        jtxtCerca = new javax.swing.JTextField();
        jbtXbox = new javax.swing.JButton();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn.setText("Login ");
        jPanel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        passwordField.setText("jPasswordField1");
        jPanel2.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sfonfopass.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtCerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerca.png"))); // NOI18N
        jbtCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCercaActionPerformed(evt);
            }
        });

        jbtPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        jbtPC.setBorder(null);
        jbtPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPCActionPerformed(evt);
            }
        });

        jbtNintendo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nintendo.png"))); // NOI18N
        jbtNintendo.setBorder(null);
        jbtNintendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNintendoActionPerformed(evt);
            }
        });

        jbtPS4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ps4.png"))); // NOI18N
        jbtPS4.setBorder(null);
        jbtPS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPS4ActionPerformed(evt);
            }
        });

        jtxtCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCercaActionPerformed(evt);
            }
        });

        jbtXbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xbox.png"))); // NOI18N
        jbtXbox.setBorder(null);
        jbtXbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jtxtCerca, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jbtCerca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbtNintendo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbtPS4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbtPC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbtXbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCerca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCerca))
                .addGap(50, 50, 50)
                .addComponent(jbtNintendo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jbtPS4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jbtPC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jbtXbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCercaActionPerformed
      //PER DATABASE
    }//GEN-LAST:event_jtxtCercaActionPerformed

    private void jbtCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCercaActionPerformed
        btn=new JButton();
        try {
          //PER DATABASE       
         btn.setName(connesione.select(jtxtCerca.getText(), scelta));
         // btn.Text("boi");
          btn.setSize(500, 90);
          btn.setLocation(150, 120);
          btn.setVisible(true);
          this.add(btn);
     } catch (SQLException ex) {
          Logger.getLogger(GUIMain.class.getName()).log(Level.SEVERE, null, ex);
      }
        
      
    }//GEN-LAST:event_jbtCercaActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
      //PER DATABASE 
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void jbtNintendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNintendoActionPerformed
       scelta="nintendo";
        
       btn=new JButton();
          btn.setSize(500, 90);
          btn.setLocation(150, 120);
          btn.setVisible(true);
          btn.setText("boi");
          //btn.setComponentPopupMenu(txtpopup=new JTextArea());
          this.add(btn);
    }//GEN-LAST:event_jbtNintendoActionPerformed

    private void jbtXboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXboxActionPerformed
       scelta="xbox";
       btn=new JButton();
        btn.setSize(500, 90);
          btn.setLocation(150, 120);
          btn.setVisible(true);
          this.add(btn);
    }//GEN-LAST:event_jbtXboxActionPerformed

    private void jbtPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPCActionPerformed
       scelta="pc";
       btn=new JButton();
        btn.setSize(500, 90);
          btn.setLocation(150, 120);
          btn.setVisible(true);
          this.add(btn);
    }//GEN-LAST:event_jbtPCActionPerformed

    private void jbtPS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPS4ActionPerformed
       scelta="ps4";
       btn=new JButton();
        btn.setSize(500, 90);
          btn.setLocation(150, 120);
          btn.setVisible(true);
          this.add(btn);
    }//GEN-LAST:event_jbtPS4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtCerca;
    private javax.swing.JButton jbtNintendo;
    private javax.swing.JButton jbtPC;
    private javax.swing.JButton jbtPS4;
    private javax.swing.JButton jbtXbox;
    private javax.swing.JTextField jtxtCerca;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
