package progettoscuola;

import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Emanuel
 */
public class GUIMain extends javax.swing.JFrame {
  static String scelta;
    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        initComponents();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        userNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jbtCerca = new javax.swing.JButton();
        jtxtCerca = new javax.swing.JTextField();
        jbtNintendo = new javax.swing.JButton();
        jbtPC = new javax.swing.JButton();
        jbtPS4 = new javax.swing.JButton();
        jbtXbox = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel2.setLayout(null);

        loginBtn.setText("Login ");
        jPanel2.add(loginBtn);
        loginBtn.setBounds(310, 310, 61, 23);

        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(userNameField);
        userNameField.setBounds(240, 180, 213, 20);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(240, 129, 72, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(240, 230, 72, 19);

        passwordField.setText("jPasswordField1");
        jPanel2.add(passwordField);
        passwordField.setBounds(240, 260, 213, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sfonfopass.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(-60, -30, 730, 480);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jDesktopPane1);
        jDesktopPane1.setBounds(510, 60, 100, 100);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(null);

        jbtCerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerca.png"))); // NOI18N
        jbtCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCercaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtCerca);
        jbtCerca.setBounds(520, 40, 20, 20);

        jtxtCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCercaActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtCerca);
        jtxtCerca.setBounds(170, 40, 344, 20);

        jbtNintendo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nintendo.png"))); // NOI18N
        jbtNintendo.setBorder(null);
        jbtNintendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNintendoActionPerformed(evt);
            }
        });
        jPanel3.add(jbtNintendo);
        jbtNintendo.setBounds(10, 110, 40, 40);

        jbtPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        jbtPC.setBorder(null);
        jbtPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPCActionPerformed(evt);
            }
        });
        jPanel3.add(jbtPC);
        jbtPC.setBounds(10, 210, 40, 40);

        jbtPS4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ps4.png"))); // NOI18N
        jbtPS4.setBorder(null);
        jbtPS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPS4ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtPS4);
        jbtPS4.setBounds(10, 260, 40, 40);

        jbtXbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xbox.png"))); // NOI18N
        jbtXbox.setBorder(null);
        jbtXbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXboxActionPerformed(evt);
            }
        });
        jPanel3.add(jbtXbox);
        jbtXbox.setBounds(10, 160, 40, 40);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tetris-effect-normal-hero-01-ps4-us-05jun18.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 770, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCercaActionPerformed
      //PER DATABASE
    }//GEN-LAST:event_jtxtCercaActionPerformed

    private void jbtCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCercaActionPerformed
      //PER DATABASE
    }//GEN-LAST:event_jbtCercaActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
      //PER DATABASE
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void jbtNintendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNintendoActionPerformed
       scelta="nintendo";
    }//GEN-LAST:event_jbtNintendoActionPerformed

    private void jbtXboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXboxActionPerformed
       scelta="xbox";
    }//GEN-LAST:event_jbtXboxActionPerformed

    private void jbtPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPCActionPerformed
       scelta="pc";
    }//GEN-LAST:event_jbtPCActionPerformed

    private void jbtPS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPS4ActionPerformed
       scelta="ps4";
    }//GEN-LAST:event_jbtPS4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtCerca;
    private javax.swing.JButton jbtNintendo;
    private javax.swing.JButton jbtPC;
    private javax.swing.JButton jbtPS4;
    private javax.swing.JButton jbtXbox;
    private javax.swing.JTextField jtxtCerca;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
